# - Available icons: https://simplelineicons.github.io/


title = "NFEF-FCUL"
baseurl = "/"
languageCode = "pt-pt"
theme = "elate"


[params]
  # custom css
  custom_css = ["/css/custom1.css", "/css/custom2.css"]

  # meta
  author = ""
  description = ""
  email = "nfef-fcul@fc.ul.pt"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # navegação
  [params.navigation]
    brand = "NFEF"
    #home = "Home"
    #work = "Iniciativas"
    #testimonials = "Testimonials"
    #services = "Services"
    #about = "Pessoas"
    #counters = "Estatísticas"
    #contact = "Contactos"

    # prepended links
    #[[menu.postpend]]
    #  url = "/page/events"
    #  name = "Iniciativas"
    #  weight = 1

    #[[menu.postpend]]
    #  url = "https://200819jkpohzg7m4mku.nextcloud.hosting.zone/s/ScroLsZRG7W5W7b"
    #  name = "Banco de Apontamentos"
    #  weight = 3

    #[[menu.postpend]]
    #  url = "/page/team"
    #  name = "Pessoas"
    #  weight = 4

    [[menu.postpend]]
      url = "/page/contact"
      name = "Contactos"
      weight = 5

    # postpended links
    # [[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10


  # hero
  [params.hero]
    title = "Núcleo de Física e Engenharia Física"
    subtitle = 'Faculdade de Ciências da Universidade de Lisboa'


  # intro
  [params.intro]
  [[params.intro.item]]
    title = "Quem somos?"
    description = "O NFEF-FCUL é o núcleo de estudantes de Física e Engenharia Física da FCUL. Vem conheçer o teu núcleo!"
    url = "/page/team"
    button = "Pessoas"
    icon = "icon-people"
    img = "bg.jpg"

  [[params.intro.item]]
    title = "Eventos"
    description = "Conheçe todos os eventos dinamizados pelo teu núcleo. De workshops a convívios, não percas estas oportunidades!"
    url = "/page/events"
    button = "Eventos"
    icon = "icon-calendar"
    img = "bg.jpg"

  [[params.intro.item]]
    title = "Queres falar connosco?"
    description = "E-mail, redes sociais e até o um canal de Discord onde podes comunicar livremente connosco e com os teus colegas!"
    url = "/page/"
    button = "Contactos"
    icon = "icon-envelope"
    img = "bg.jpg"


  # o que fazemos?
  [params.services]
    enable = true
    title = "O que fazemos?"
    description = "Ficam aqui algumas das atividades dinamizadas pelo teu núcleo."

    [[params.services.item]]
      title = "Física Fora da Academia"
      description = "Estás num curso de Física, e agora? Numa maratona de palestras vem descobrir tudo o que fazem os antigos alunos dos cursos de Física e Engenharia Física que hoje trabalham na indústria. Visita a página 'iniciativas' para saberes mais!"
      icon = "icon-people"

    [[params.services.item]]
      title = "Workshops"
      description = "A faculdade dá-te as hard skills que precisas para o teu futuro, porque não investires o teu tempo a treinar as tuas soft skills também? O teu núcleo disponibiliza vários workshop ao longo do ano, visita a página 'iniciativas' para mais informação!"
      icon = "icon-wrench"

    [[params.services.item]]
      title = "Programa de Mentores"
      description = "Vai começar uma nova etapa da tua vida, com novos desafios, pessoas e experiências. Porquê não pedir uma ajuda para te guiar nestes novos caminhos? Com o Programa de Mentores cada aluno do 1º ano pode ter o seu próprio mentor para ajudar tanto nas aulas como na integração no meio académico."
      icon = "icon-graduation"

    [[params.services.item]]
      title = "Convívio"
      description = "Depois de todo o esforço feito dentro e fora de aulas podes agora usufruir de vários momentos de convivio organizados pelo teu núcleo, aberto para todos os interessados. Desde a churrascos até noites que Quizzes visita a página 'iniciativas' para descobrir quando e onde é o próximo evento!"
      icon = "icon-bubbles"


  # quantos somos?
  [params.counters]
    enable = true
    title = "Quantos somos?"
    #background = "quadro_fisica.jpg"

    [[params.counters.item]]
      description = "Estudantes"
      icon = "icon-graduation"
      from = 0
      to = 89
      interval = 50
      speed = 1000

    [[params.counters.item]]
      description = "Membros"
      icon = "icon-people"
      from = 0
      to = 22
      interval = 50
      speed = 1000

    [[params.counters.item]]
      description = "Sócios"
      icon = "icon-heart"
      from = 0
      to = 9000
      interval = 50
      speed = 1000


  # video
  #[params.intro.video]
  #  enable = true
  #  title = "Watch the video"
  #  icon = "icon-play2"
  #  url = ""


  # proximos eventos
  [params.work]
    enable = true
    titleNext = "Próximos eventos"
    descriptionNext = "Os próximos eventos dinamizados pelo teu núcleo para toda a comunidade estudantil"
    #footertext = ""

    [[params.work.row]]
      img = "ffa.jpg"
      alt = "Image2"
      title = "Física Fora da Academia"
      subtitle = "Dia 45 de Setembro de 2049"

    [[params.work.row]]
      img = "churrasco.jpg"
      alt = "Image4"
      title = "Churrasco"
      subtitle = "Dia 32 de Novembro de 2069"

    [[params.work.row]]
      img = "churrasco.jpg"
      alt = "Image4"
      title = "Churrascod"
      subtitle = "Dia 32 de Novembro de 2069"


  # iniciativas
  [params.iniciativas]
    enable = true
    title = "Iniciativas"
    description = "Apresentamos aqui todos os eventos dinamizados pelo teu núcleo para toda a comunidade estudantil"
    #footertext = ""

    [[params.iniciativas.row]]
      img = "ffa.jpg"
      alt = "Image2"
      title = "Física Fora da Academia"
      subtitle = "Interessado numa carreira na industria? Este evento é para ti!"

    [[params.iniciativas.row]]
      img = "placeholder.png"
      alt = "Image3"
      title = "Programa de Mentorandos"
      subtitle = "Alguém para te ajudar no início da tua vida académica."

    [[params.iniciativas.row]]
      img = "churrasco.jpg"
      alt = "Image4"
      title = "Banco de Apontamentos"
      subtitle = "Uma pausa de todos os trabalhos da faculdade"

    [[params.iniciativas.row]]
      img = "placeholder.png"
      alt = "Image4"
      title = "Workshops"
      subtitle = "Todo o material complementar necessário para o teu estudo"

    [[params.iniciativas.row]]
      img = "placeholder.png"
      alt = "Image4"
      title = "Revista Dº"
      subtitle = "Uma série de workshops para complementares a tua formação"

    [[params.iniciativas.row]]
      img = "trivia.png"
      alt = "Image3"
      title = "NFEF Trivia"
      subtitle = "Desafios para além dos desafios das aulas"
    
    [[params.iniciativas.row]]
      img = "churrasco.jpg"
      alt = "Image4"
      title = "Notas Comunitárias"
      subtitle = "Uma pausa de todos os trabalhos da faculdade"

    [[params.iniciativas.row]]
      img = "churrasco.jpg"
      alt = "Image4"
      title = "Discord"
      subtitle = "Uma pausa de todos os trabalhos da faculdade"

  # testimonials
  #[params.testimonials]
  #  enable = true
  #  title = "Testimonials"
  #  description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

  #  [[params.testimonials.item]]
  #    quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
  #    person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
  #    img = "person1.jpg"
  #    alt = "Person1"

  #  [[params.testimonials.item]]
  #    quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
  #    person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
  #    img = "person2.jpg"
  #    alt = "Person2"

  #  [[params.testimonials.item]]
  #    quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
  #    person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
  #    img = "person3.jpg"
  #    alt = "Person3"


  # pessoas
  [params.about]
    enable = true
    title = "Pessoas"
    #description = ""

    # direcao
    [[params.about.item]]
      name = "Rita Pestana"
      position = "Secretária"
      #description = ""
      img = "person1.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    [[params.about.item]]
      name = "Rafael Pinto"
      position = "Tesoureiro"
      #description = ""
      img = "person2.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    [[params.about.item]]
      name = "Rita Reis"
      position = "Coordenadora do Pedagógico"
      #description = ""
      img = "person3.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    [[params.about.item]]
      name = "Miguel Pinto"
      position = "Vogal do Pedagógico"
      #description = ""
      img = "person1.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    [[params.about.item]]
      name = "João Neves"
      position = "Coordenador da Imagem/Divulgação"
      #description = ""
      img = "person2.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    [[params.about.item]]
      name = "Ariana Dias"
      position = "Vogal da Imagem/Divulgação"
      #description = ""
      img = "person3.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    [[params.about.item]]
      name = "Ana Benquerença"
      position = "Coordenador do Recreativo"
      #description = ""
      img = "person1.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    [[params.about.item]]
      name = "Constança Freire"
      position = "Vogal do Recreativo"
      #description = ""
      img = "person2.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    # conselho fiscal
    [[params.about.item]]
      name = "Nuno Taborda"
      position = "Presidente do Fiscal"
      #description = ""
      img = "person3.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    [[params.about.item]]
      name = "Sílvia Costa"
      position = "Vice-Presidente do Fiscal"
      #description = ""
      img = "person1.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    [[params.about.item]]
      name = "Gonçalo Fernandes"
      position = "Secretário do Fiscal"
      #description = ""
      img = "person2.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    # assembeleia geral
    [[params.about.item]]
      name = "Rui Vieira"
      position = "Presidente da Mesa"
      #description = ""
      img = "person3.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    [[params.about.item]]
      name = "Inês Caipiro"
      position = "Vice-Presidente da Mesa"
      #description = ""
      img = "person1.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    [[params.about.item]]
      name = "Diogo Matos"
      position = "Vogal da Mesa"
      #description = ""
      img = "person2.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    # pedagogico
    [[params.about.item]]
      name = "Mafalda Nunes"
      #position = ""
      #description = ""
      img = "person3.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    [[params.about.item]]
      name = "Rodrigo Lopes"
      #position = ""
      #description = ""
      img = "person1.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    [[params.about.item]]
      name = "Bernardo Gameiro"
      #position = ""
      #description = ""
      img = "person2.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    [[params.about.item]]
      name = "Eduardo Batista"
      #position = ""
      #description = ""
      img = "person3.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    # recreativo
    [[params.about.item]]
      name = "João Belo"
      #position = ""
      #description = ""
      img = "person1.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    # imagem
    [[params.about.item]]
      name = "Carolina Felgueiras"
      #position = ""
      #description = ""
      img = "person2.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    [[params.about.item]]
      name = "José Ferreira"
      #position = ""
      #description = ""
      img = "person3.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]

    [[params.about.item]]
      name = "Ricardo Honório"
      #position = ""
      #description = ""
      img = "person1.jpg"
      social = [["icon-globe", "https://example.com"], ["icon-envelope", "mailto:john@example.com"], ["icon-linkedin", "https://www.linkedin.com/in/example/"], ["icon-github", "https://github.com/example"]]


  # Contactos
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Contactos"
    description = ""

    details = [
        ["icon-home", "Edíficio C8 Piso 4 Sala 17, 1749-016 Campo Grande, Lisboa, Portugal"],
        ["icon-envelope", "nfef-fcul@fc.ul.pt"],
        ["icon-facebook", "https://www.facebook.com/NFEFFCUL/"],
        ["icon-instagram", "https://www.instagram.com/nfeffcul/"],
        ["icon-linkedin", "https://www.linkedin.com/company/nfef-fcul/"],
        ["icon-github", "https://github.com/NFEF-FCUL"],
      ]

    name = "Nome"
    email = "E-mail"
    #phone = "Phone"
    message = "Mensagem"
    button = "Enviar Mensagem"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Página feita com Hugo, baseado no tema Elate. Código disponível na nossa página do Github."
    links = [
        ["icon-facebook", "https://www.facebook.com/NFEFFCUL/"],
        ["icon-instagram", "https://www.instagram.com/nfeffcul/"],
        ["icon-linkedin", "https://www.linkedin.com/company/nfef-fcul/"],
      ]
